export const itemsEstructura = [
  { nombre: 'descripcion',
    default: 'null',
    tipo: 'String',
    descripcion: 'Contiene la descripción de la propiedad, soporta estructuras html <img src="https://cdn.iconscout.com/icon/premium/png-64-thumb/html-126-287291.png" height="40px" >.' },
  { nombre: 'default',
    default: 'null',
    important: 'true',
    tipo: 'String',
    descripcion: 'Contiene el valor por defecto de la propiedad, si no se modifica no se muestra.' },
  { nombre: 'nombre',
    default: 'prop${index}',
    important: 'true',
    tipo: 'String',
    descripcion: 'Contiene el nombre de la propiedad.' },
  { nombre: 'tipo',
    default: 'null',
    important: 'true',
    tipo: 'String',
    descripcion: 'Contiene el tipo de valor que espera la propiedad, si no se modifica no se muestra.' }
]