export const propsPicker = [
  { nombre: 'v-model',
    important: true,
    tipo: 'Array, Object',
    descripcion: 'Es la propiedad que recibira el resultado del Componente. Los datos deben estar estructurados de acuerdo a la pestaña de <b style="font-size:15px">Estructura Respuesta</b> para que el componente mustre los datos' },
  { nombre: 'append-icon',
    default: '""',
    tipo: 'String',
    descripcion: 'Icono al final de la Caja de Texto.' },
  { nombre: 'append-outer-no-margin',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'agrega una clase al <b>append-out-icon</b> que remueve el margen.' },
  { nombre: 'append-out-icon',
    default: '""',
    tipo: 'String',
    descripcion: 'Icono al final y afuera de la Caja de Texto.' },
  { nombre: 'attach-icon',
    default: '"attach_file"',
    important: true,
    tipo: 'String',
    descripcion: 'Icono al principio de la caja de texto, responde al click.' },
  { nombre: 'autofocus',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'El Campo de Texto recibe el Foco automaticamente.' },
  { nombre: 'background',
    default: '""',
    tipo: 'String',
    descripcion: 'Color de Fondo de la Caja de Texto.' },
  { nombre: 'box',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en estilo Box.' },
  { nombre: 'color',
    default: 'primary',
    tipo: 'String',
    descripcion: 'Define el color de la Caja de Texto.' },
  { nombre: 'counter',
    default: '10',
    tipo: 'String',
    descripcion: 'Define un contador de caracteres de la Caja de Texto.' },
  { nombre: 'dark',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en estilo Oscuro.' },
  { nombre: 'disabled',
    default: 'false',
    important: true,
    tipo: 'Boolean',
    descripcion: 'Caja de Texto Desactivada. Desactiva las acciones de seleccionar y limpiar' },
  { nombre: 'hide-details',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Desactiva los detalles y mensajes de la Caja de Texto.' },
  { nombre: 'hint',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra una Ayuda al Escribir en la Caja de Texto.' },
  { nombre: 'img-default',
    default: '"image"',
    tipo: 'String',
    important: true,
    descripcion: 'Contiene el identificador de la imagén por defecto de la lista de <b>Default Images</b>.' },
  { nombre: 'input-accept',
    default: '"*"',
    tipo: 'String',
    important: true,
    descripcion: 'Contiene el tipo de archivo que puede seleccionar el input (<a href="https://www.w3schools.com/tags/att_input_accept.asp"> Más Información ...</a>); Si se selecciona un archivo que no es aceptado desencadenará un error. ' },
  { nombre: 'is-collections',
    default: 'false',
    important: true,
    tipo: 'Boolean',
    descripcion: 'Define si se pueden seleccionar múltiples archivos.' },
  { nombre: 'is-vertical',
    default: 'false',
    important: true,
    tipo: 'Boolean',
    descripcion: 'Define si la vista previa se coloca arriba de la caja de texto.' },
  { nombre: 'label',
    default: '"Seleccione un Archivo"',
    tipo: 'String',
    important: true,
    descripcion: 'Muestra una Etiqueta en la Caja de Texto. Puede ser sobre-escrito por el slot="label"' },
  { nombre: 'loading',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en Modo Loading. ' },
  { nombre: 'max-mb',
    default: '4',
    important: true,
    tipo: 'Number, String',
    descripcion: 'Maneja el límite de MegaBytes que pueden tener los archivos que se seleccionan. ' },
  { nombre: 'persistent-hint',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto con el Hint de Manera Permanente. ' },
  { nombre: 'placeholder',
    default: '" "',
    tipo: 'String',
    important: true,
    descripcion: 'Muestra un texto temporal dentro de la Caja de Texto.' },
  { nombre: 'prefix',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un texto Permanente al Inicio de la Caja de Texto.' },
  { nombre: 'prepend-icon',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un icono al Inicio de la Caja de Texto.' },
  { nombre: 'prepend-out-icon',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un icono al Inicio y afuera de la Caja de Texto.' },
  { nombre: 'preview-size',
    default: '50',
    important: true,
    tipo: 'Number, String',
    descripcion: 'Define el tamaño de la vista previa.' },
  { nombre: 'outline',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Outline a la Caja de Texto. ' },
  { nombre: 'remove-icon',
    default: '"highlight_off"',
    important: true,
    tipo: 'String',
    descripcion: 'Define el icono para limpiar el modelo, así como el icono para quitar un elemento de los archivos multiples' },
  { nombre: 'required',
    default: 'false',
    important: true,
    tipo: 'Boolean',
    descripcion: 'Aplica a la caja de texto la regla de requerido.' },
  { nombre: 'reverse',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Invierte la Orientacion de la Caja de Texto, de izquierda a derecha.' },
  { nombre: 'rules',
    default: '[]',
    tipo: 'Array',
    descripcion: 'Colección de Reglas con las cuales se valida el contenido de la Caja de Texto.' },
  { nombre: 'solo',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Solo a la Caja de Texto. ' },
  { nombre: 'solo-inverted',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Solo Invertido a la Caja de Texto. ' },
  { nombre: 'suffix',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra un texto Permanente al Final de la Caja de Texto.' }
]