export const propsPicker = [
  { nombre: 'v-model',
    important: true,
    tipo: 'Array, Object',
    descripcion: 'Es la propiedad que recibira el resultado del Componente. Los datos deben estar estructurados de acuerdo a la pestaña de <b style="font-size:15px">Props Modelo</b> para que el componente mustre los datos' },
  { nombre: 'append-icon',
    default: '""',
    tipo: 'String',
    descripcion: 'Icono al final de la Caja de Texto.' },
  { nombre: 'append-outer-no-margin',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'agrega una clase al <b>append-out-icon</b> que remueve el margen.' },
  { nombre: 'append-out-icon',
    default: '""',
    tipo: 'String',
    descripcion: 'Icono al final y afuera de la Caja de Texto.' },
  { nombre: 'attachIcon',
    default: '"attach_file"',
    important: true,
    tipo: 'String',
    descripcion: 'Icono al principio de la caja de texto, responde al click.' },
  { nombre: 'autofocus',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'El Campo de Texto recibe el Foco automaticamente.' },
  { nombre: 'background',
    default: '""',
    tipo: 'String',
    descripcion: 'Color de Fondo de la Caja de Texto.' },
  { nombre: 'box',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en estilo Box.' },
  { nombre: 'color',
    default: 'primary',
    tipo: 'String',
    descripcion: 'Define el color de la Caja de Texto.' },
  { nombre: 'counter',
    default: '10',
    tipo: 'String',
    descripcion: 'Define un contador de caracteres de la Caja de Texto.' },
  { nombre: 'dark',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en estilo Oscuro.' },
  { nombre: 'disabled',
    default: 'false',
    important: true,
    tipo: 'Boolean',
    descripcion: 'Caja de Texto Desactivada.' },
  { nombre: 'hide-details',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Desactiva los detalles y mensajes de la Caja de Texto.' },
  { nombre: 'hint',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra una Ayuda al Escribir en la Caja de Texto.' },
  { nombre: 'img-default',
    default: '"image"',
    tipo: 'String',
    descripcion: 'Contiene el identificador de la imagén por defecto de la lista de <b>Default Images</b>.' },
  { nombre: 'input-accept',
    default: '"*"',
    tipo: 'String',
    descripcion: 'Contiene el tipo de archivo que puede seleccionar el input; <span class="font-weight-medium red--text"> En plataformas diferentes a <b>web</b> cuando se requieren <b>multiples archivos</b> sólo pueden seleccionarse imagenes </span>.' },
  { nombre: 'label',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra una Etiqueta en la Caja de Texto.' },
  { nombre: 'loading',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en Modo Loading. ' },
  { nombre: 'no_resize',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Quita el Control de tamaño del TextArea. ' },
  { nombre: 'mask',
    default: '""',
    tipo: 'String',
    descripcion: 'Aplica Una Mascara al Texto Ingresado. ' },
  { nombre: 'maxlength',
    default: '""',
    tipo: 'Number | String',
    descripcion: 'Aplica Una Limite de Caracteres al Texto Ingresado. ' },
  { nombre: 'persistent_hint',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto con el Hint de Manera Permanente. ' },
  { nombre: 'placeholder',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra un texto temporal dentro de la Caja de Texto.' },
  { nombre: 'prefix',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un texto Permanente al Inicio de la Caja de Texto.' },
  { nombre: 'prepend_icon',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un icono al Inicio de la Caja de Texto.' },
  { nombre: 'prepend_out_icon',
    default: '',
    tipo: 'String',
    descripcion: 'Muestra un icono al Inicio y afuera de la Caja de Texto.' },
  { nombre: 'outline',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Outline a la Caja de Texto. ' },
  { nombre: 'readonly',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Caja de Texto en Modo Solo Lectura.' },
  { nombre: 'remmoveIcon',
    default: 'clear',
    tipo: 'String',
    descripcion: 'Define el icono para borrar.' },
  { nombre: 'rec_icon',
    default: 'mic',
    tipo: 'String',
    descripcion: 'Maneja el Icono de Iniciar Dictado',
    important: true },
  { nombre: 'required',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica a la caja de texto reglas (si no cuenta con ninguna), y un marcador de requerido a la Etiqueta (solo si tiene etiqueta).' },
  { nombre: 'reverse',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Invierte la Orientacion de la Caja de Texto, de izquierda a derecha.' },
  { nombre: 'rows',
    default: '5',
    tipo: 'Number | String',
    descripcion: 'Define el número de lineas del Text Area.' },
  { nombre: 'rules',
    default: '[]',
    tipo: 'Array',
    descripcion: 'Colección de Reglas con las cuales se valida el contenido de la Caja de Texto.' },
  { nombre: 'small',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Reduce las dimensiones de la caja de texto/Text Area ',
    important: true },
  { nombre: 'solo',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Solo a la Caja de Texto. ' },
  { nombre: 'solo_inverted',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Aplica el estilo Solo Invertido a la Caja de Texto. ' },
  { nombre: 'suffix',
    default: '""',
    tipo: 'String',
    descripcion: 'Muestra un texto Permanente al Final de la Caja de Texto.' }
]